language: R
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  include:
    - os: linux
      env: RVERSION=release
      r_github_packages:
        - jimhester/covr
      after_success:
        - grep -q -R "warning" "${RCHECK_DIR}/00install.out"
        - travis_wait 30 Rscript -e 'covr::codecov(line_exclusions="src/pomp.h")'
    - os: linux
      env: RVERSION=3.1.2
      after_success:
        - grep -q -R "warning" "${RCHECK_DIR}/00install.out"
    - os: linux
      env: RVERSION=devel
      after_success:
        - grep -q -R "warning" "${RCHECK_DIR}/00install.out"
    - os: osx
      env: RVERSION=release
      after_success:
        - grep -q -R "warning" "${RCHECK_DIR}/00install.out"
    - os: osx
      env: RVERSION=devel
      after_success:
        - grep -q -R "warning" "${RCHECK_DIR}/00install.out"
