language: r
sudo: false
cache: packages
file_glob: true
latex: false
pandoc: false
addons:
  apt:
    packages:
    - libgit2-dev
  homebrew:
    packages:
    - libgit2
stages:
- test
- coverage
- name: deploy
  if: tag IS present
jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: 3.4
    os: linux
  - r: release
    os: osx
  - r: devel
    os: osx
  - stage: coverage
    r: release
    os: linux
    r_packages:
    - covr
    script:
    - travis_wait 30 Rscript -e 'covr::codecov()'
  - stage: deploy
    r: release
    os: osx
    script:
    - R CMD build .
    - mkdir -p plib
    - TARBALL=$(ls -1t *.tar.gz)
    - R CMD INSTALL --build -l plib ${TARBALL}
    - rm -rf plib
    deploy:
      provider: releases
      api-key:
        secure: V0UAes1YbF80zUnOhV8W3fgL16R3s6Dp28LxHT/Z07HaZruI1SnuNrxLRCLG54sY+7WKrZUz7d8hAYMQmDNDWmctAffBgomy4lKsXhi6OiytFbWi+8np616syzqB0kfF14wysqF8dldGFXd4ArHIx4JGmsPiAbiWx3mBaYtrqmG6rhCpD6+tM+EttK4n8eg6c1Mq0rnbmJd+0ZlSYz+55ueTsGv1zF14oScI/+C1ghHgwAghzhvFtTimTCU7dkLxFoZtTD1WEHDdqwsqwfr++vyM7GkTi/gvxxIMgB0fH1NkgRt+VMutODv49qX1E5PoLE7KoQI9zy0ij20n+O0waGVvM6fTlaxf+qb+UnCs7hypwFFGLb3eMJgmcptWEs048KjHcnEv8etMeYYF+ljkQ4euMoDoBMPE+7yLFRyWihI0gsBBRfvOFeab1PnSXuMCojxfwMz+gsdOt5wfgWR2fycQ5hpDMS58W+UgGML7FbQyd8smw8xIyBFSxfO9APgrNoLG86atmPv27pDPoEw2q7D98OPHZXt/j7lrA59TyEOi4DpozoyW37RKhqLkOEjxJOz+NM2u9duIMdNgOuq2qfuAiJRFqhEKvA5dArZadJEzUlzjGUUWKlmiTHeAkiJE0+3tuS5PgkC1VuuxYE42TYFfQHalf2gJsU4VfCj4Ji8=
      file_glob: true
      file:
      - pomp_*.tgz
      - pomp_*.tar.gz
      skip_cleanup: true
      on:
        tags: true
