# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '13 11 * * 0'
  push:
    branches:
      - '*'
    paths:
      - DESCRIPTION
      - NAMESPACE
      - R/**
      - src/**
      - tests/**
      - man/**
      - data/**
  pull_request:
    paths:
      - DESCRIPTION
      - NAMESPACE
      - R/**
      - src/**
      - tests/**
      - man/**
      - data/**
  workflow_dispatch:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-22.04,   r: '4.1.0'}
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: |
            https://kingaa.github.io/

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::tidyr
            any::ggplot2
            any::dplyr
            any::knitr
            any::subplex
            any::nloptr

      - uses: r-lib/actions/check-r-package@v2

      - uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}-results
          path: check/${{ vars.repo_name }}.Rcheck/00check.log
